version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/
  
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: root
  AferInstall:
    - location: scripts/after.sh
      timeout: 600
      runas: root
