version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/
  
hooks:
  BeforeInstall:
    - location: scripts/before.sh
    - timeout: 100
    - runsas: root
  AfterInstall:
    - location: scripts/after.sh
    - timeout: 100
    - runas: root
  
