version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/
  
hooks:
  BeforeInstall:
    - location: before.sh
    - timeout: 100s
    - runsas: root
  AfterInstall:
    - location: after.sh
    - timeout: 100s
    - runas: root
  
